training_parameters:
  batch_size: 10000
  batch_buffer_size: 100
  train_size: 0.7
  scale_features: standard
  shuffle: true
features:
- n_MissingHits
- n_Hits
- ax
- bx
- cx
arch_parameters:
  n_features: 18
  n_classes: 2
  n_nodes: [18,10,5,2]
  monotone_constraints: [0,0,0]
